apiVersion: cluster.open-cluster-management.io/v1alpha1
kind: Placement
metadata:
  name: book-info-placement
  namespace: default
spec:
    predicates:
    - requiredClusterSelector:
        labelSelector:
          matchLabels:
            environment: dev